import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { existsSync, writeFileSync } from 'node:fs';
import { captureReleaseSourceSnapshot, createBuildIdentity } from './lib/release-identity.mjs';
import { clearBuildSourceDiagnostics, writeBuildSourceDiagnostics } from './lib/build-source-diagnostics.mjs';

const require = createRequire(import.meta.url);
const before = captureReleaseSourceSnapshot();
clearBuildSourceDiagnostics();
const astroPackage = require.resolve('astro/package.json');
const astroBin = join(dirname(astroPackage), require(astroPackage).bin.astro);
const result = spawnSync(process.execPath, [astroBin, 'build'], { stdio: 'inherit', windowsHide: true });
if (result.status !== 0) process.exit(result.status ?? 1);
if (!existsSync('dist/client')) throw new Error('Astro build produced no dist/client; build identity was not written.');
await import('./mirror-static-output.mjs');
const after = captureReleaseSourceSnapshot();
const identity = createBuildIdentity(before.source, after.source);
writeBuildSourceDiagnostics(before, after, identity);
for (const dir of ['dist/client', 'dist']) writeFileSync(join(dir, '_build.json'), `${JSON.stringify(identity, null, 2)}\n`);
console.log(`Build source identity: ${identity.commit ?? 'unavailable'}; ${identity.clean ? 'clean' : 'unverified'}.`);
